config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users, controllers: { invitations: 'admin/invitations' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups

  scope :public_access, -> { where(is_private: false) }
  scope :private_access, -> { where(is_private: true) }

  def is_admin?(user_id)
    self.user_groups.with_admin.find_by_user_id(user_id).present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :invitable

  enum designation: { user: 0, admin: 1, super_admin: 2 }
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :group
  belongs_to :user

  enum user_type: { member: 0, admin: 1 }

  scope :with_admin, -> { where(user_type: 1) }
  scope :with_member, -> { where(user_type: 0) }
end

app/controllers/admin/invitations_controller.rb
class Admin::InvitationsController < Devise::InvitationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:invite, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:accept_invitation, keys: [:name, :password, :password_confirmation, :birthday, :designation, :nickname])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ActionController::Base
  before_action :set_group, only: %i[show member_index non_member_index add_member]

  def show
  end

  def member_index
    @users = @group.users
  end

  def non_member_index
    @non_member_users = User.all - @group.users
  end

  def add_member
    user = User.find_by_id(params[:user_id])
    @group.users << user
    flash[:succes] = "Member added successfully"
    redirect_to non_member_index_group_path
  end

  private

  def set_group
    @group = Group.find_by_id(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def profile
    @user = User.unscoped.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/member_index.html.erb
<%= link_to "All Non-Member Users", non_member_index_group_path(@group) %>

<p> All Members </p>
<% @group.users.each do |user| %>
  <span><%= user.email %></span> : <span><%= @group.is_admin?(user.id) ? "Admin" : "Member" %></span>
  <br>
<% end %>

app/views/groups/non_member_index.html.erb
<p> All Non-member User </p>
<% @non_member_users.each do |user| %>
  <span><%= user.email %></span>
  <%# Must update this to patch request type %>
  <%= link_to "Add", add_member_group_path(@group, user) %>
  <br>
<% end %>

app/views/groups/show.html.erb
<p><%= @group.name %></p>
<p><%= @group.description %></p>

<%= link_to "View All Non-Members", non_member_index_group_path(@group) %>
<br>
<%= link_to "View All Members", member_index_group_path(@group) %>

app/views/home/index.html.erb
<%= render "shared/navbar" %>

<h1>Welcome to Jango Management System</h1>
<p>Big things are comming, so stay tunned!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jango</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<%= link_to "Login", new_user_session_path %>

<%= link_to "Send Invite", new_user_invitation_path %>

app/views/users/profile.html.erb
<p>As Member</p>
<% @user.groups_as_member.each do |group| %>
  <span><%= group.name %></span> : <%= link_to "View Group", group_path(group) %>
  <br>
<% end %>

<p>As Admin</p>
<% @user.groups_as_admin.each do |group| %>
  <span><%= group.name %></span> : <%= link_to "View Group", group_path(group) %>
  <br>
<% end %>